user1 = User.create!(name: "Alyssa", username: "alyssa", password: "123456")
user2 = User.create!(name: "Graham", username: "graham", password: "123456")
user3 = User.create!(name: "Avner", username: "avner", password: "123456")
user4 = User.create!(name: "Duke", username: "duke", password: "123456")
user4 = User.create!(name: "Karl", username: "karl", password: "123456")

Song.create!(title: "Your Hand in Mine", artist: "Explosions in the Sky")
Song.create!(title: "First", artist: "Cold War Kids")
Song.create!(title: "Silent Shout", artist: "The Knife")
Song.create!(title: "Bromance", artist: "Tim Berg")
Song.create!(title: "The Cave", artist: "Mumford & Sons")
Song.create!(title: "Cult of Personality", artist: "Living Colour")
Song.create!(title: "Jump on My Shoulders", artist: "AWOLNATION")
Song.create!(title: "The Perfect Drug", artist: "Nine Inch Nails")
Song.create!(title: "Röyksopp Forever", artist: "Röyksopp")
Song.create!(title: "I Still Haven't Found What I'm Looking For", artist: "U2")
Song.create!(title: "Shut up and Dance", artist: "WALK THE MOON")
Song.create!(title: "This Time Of Year", artist: "Better Than Ezra")
Song.create!(title: "Bounce", artist: "Calvin Harris")
Song.create!(title: "Pig", artist: "Dave Matthews Band")
Song.create!(title: "Santa Monica", artist: "Everclear")
Song.create!(title: "Love Is All I Got - Friction Remix", artist: "Feed Me")
Song.create!(title: "Hey Julie", artist: "Fountains of Wayne")
Song.create!(title: "Freedom! '90", artist: "George Michael")
Song.create!(title: "Stagger Lee", artist: "Lloyd Price")
Song.create!(title: "Real Love", artist: "Mary J. Blige")
Song.create!(title: "Heartbeat", artist: "Childish Gambino")
Song.create!(title: "H.O.U.S.E. (Gerd's New Vox Remix)", artist: "Gerd")
Song.create!(title: "Dirty Harry", artist: "Gorillaz")
Song.create!(title: "Punching In A Dream", artist: "The Naked And Famous")
Song.create!(title: "Ignition (Remix)", artist: "R. Kelly")
Song.create!(title: "D.A.N.C.E.", artist: "Justice")
Song.create!(title: "World On Fire", artist: "The Royal Concept")
Song.create!(title: "Shuriken", artist: "Madeon")
Song.create!(title: "Set It Off", artist: "Girl Talk")
Song.create!(title: "Too Long", artist: "Daft Punk")
