user1 = User.create!(name: "Alyssa", username: "alyssa", password: "123456")
user2 = User.create!(name: "Graham", username: "graham", password: "123456")
user3 = User.create!(name: "Avner", username: "avner", password: "123456")
user4 = User.create!(name: "Duke", username: "duke", password: "123456")
user5 = User.create!(name: "Karl", username: "karl", password: "123456")

song1 = Song.create!(title: "Your Hand in Mine", artist: "Explosions in the Sky", owner: user1)
Song.create!(title: "First", artist: "Cold War Kids", owner: user1)
Song.create!(title: "Silent Shout", artist: "The Knife", owner: user1)
Song.create!(title: "Bromance", artist: "Tim Berg", owner: user1)
Song.create!(title: "The Cave", artist: "Mumford & Sons", owner: user1)
Song.create!(title: "Cult of Personality", artist: "Living Colour", owner: user1)
song2 = Song.create!(title: "Jump on My Shoulders", artist: "AWOLNATION", owner: user2)
Song.create!(title: "The Perfect Drug", artist: "Nine Inch Nails", owner: user2)
Song.create!(title: "Röyksopp Forever", artist: "Röyksopp", owner: user2)
Song.create!(title: "I Still Haven't Found What I'm Looking For", artist: "U2", owner: user2)
Song.create!(title: "Shut up and Dance", artist: "WALK THE MOON", owner: user2)
Song.create!(title: "This Time Of Year", artist: "Better Than Ezra", owner: user2)
song3 = Song.create!(title: "Bounce", artist: "Calvin Harris", owner: user3)
Song.create!(title: "Pig", artist: "Dave Matthews Band", owner: user3)
Song.create!(title: "Santa Monica", artist: "Everclear", owner: user3)
Song.create!(title: "Love Is All I Got - Friction Remix", artist: "Feed Me", owner: user3)
Song.create!(title: "Hey Julie", artist: "Fountains of Wayne", owner: user3)
Song.create!(title: "Freedom! '90", artist: "George Michael", owner: user3)
song4 = Song.create!(title: "Stagger Lee", artist: "Lloyd Price", owner: user4)
Song.create!(title: "Real Love", artist: "Mary J. Blige", owner: user4)
Song.create!(title: "Heartbeat", artist: "Childish Gambino", owner: user4)
Song.create!(title: "H.O.U.S.E. (Gerd's New Vox Remix)", artist: "Gerd", owner: user4)
Song.create!(title: "Dirty Harry", artist: "Gorillaz", owner: user4)
Song.create!(title: "Punching In A Dream", artist: "The Naked And Famous", owner: user4)
song5 = Song.create!(title: "Ignition (Remix)", artist: "R. Kelly", owner: user5)
Song.create!(title: "D.A.N.C.E.", artist: "Justice", owner: user5)
Song.create!(title: "World On Fire", artist: "The Royal Concept", owner: user5)
Song.create!(title: "Shuriken", artist: "Madeon", owner: user5)
Song.create!(title: "Set It Off", artist: "Girl Talk", owner: user5)
Song.create!(title: "Too Long", artist: "Daft Punk", owner: user5)
